server.port: 8653
spring:
  jpa:
    properties:
      org.hibernate.envers:
        audit_table_suffix: _audit
        revision_field_name: revision
        revision_type_field_name: revision_type

  datasource:
    url: jdbc:h2:mem:spring-auditing
