server.port: 8080
spring:
  datasource:
    url: jdbc:h2:mem:spring-auditing
  jpa:
    properties:
      org.hibernate.envers:
        audit_table_suffix: _audit
        revision_field_name: revision
        revision_type_field_name: revision_type
  jackson:
    default-property-inclusion: non_default
    deserialization:
      ACCEPT_EMPTY_STRING_AS_NULL_OBJECT: true
      READ_UNKNOWN_ENUM_VALUES_USING_DEFAULT_VALUE: true
      FAIL_ON_NUMBERS_FOR_ENUMS: true
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
      WRITE_EMPTY_JSON_ARRAYS: false
      WRITE_BIGDECIMAL_AS_PLAIN: true
jwt:
  keystore:
    location: classpath:/jwt.jks
    password: H3lpM#Plz
  key:
    alias: jwt
#    password: none