POST {{host}}/oauth/token
  ?client_id={{clientId}}
  &grant_type=client_credentials
Authorization: Basic {{clientId}} {{clientSecret}}
Content-Type: application/x-www-form-urlencoded
Accept: application/json

> {%
  if( response.status === 200 ) {
    client.global.set("accessToken", response.body.access_token);
  }
%}
###
GET {{host}}/user
Authorization: Bearer {{accessToken}}
Accept: application/json

###
POST {{host}}/user
Authorization: Bearer {{accessToken}}
Content-Type: application/json
Accept: application/json

{
  "username": "mvanderlugt",
  "password": "Password1",
  "firstName": "Mark",
  "lastName": "Vander Lugt",
  "email": "mvanderlugt@live.com"
}

> {%
    if( response.status === 201 ) {
    client.global.set("userId", response.body.id);
  }
 %}
###
POST {{host}}/oauth/token
  ?client_id={{clientId}}
  &grant_type=password
Authorization: Basic {{clientId}} {{clientSecret}}
Content-Type: application/x-www-form-urlencoded
Accept: application/json

username=mvanderlugt&password=Password1

> {%
  if( response.status === 200 ) {
    client.global.set("accessToken", response.body.access_token);
  }
%}
###
GET {{host}}/user/{{userId}}
Authorization: Bearer {{accessToken}}
Accept: application/json

###
PUT {{host}}/user/{{userId}}
Authorization: Bearer {{accessToken}}
Content-Type: application/json
Accept: application/json

{
  "username": "markv",
  "password": "Password5",
  "firstName": "Mark",
  "lastName": "Vander Lugt",
  "email": "mvanderlugt1@gmail.com"
}

###
GET {{host}}/user/{{userId}}/audit
Authorization: Bearer {{accessToken}}
Accept: application/json

###
DELETE {{host}}/user/5064c768-fa81-4d3c-a215-16dce38c7199
Authorization: Bearer {{accessToken}}
Accept: application/json

###
POST {{host}}/role
Authorization: Bearer {{accessToken}}
Content-Type: application/json
Accept: application/json

{
  "name": "Administrator"
}

> {%
  if( response.status === 201 ) {
    client.global.set("roleId", response.body.id);
  }
%}

###
POST {{host}}/user/{{userId}}/role
Authorization: Bearer {{accessToken}}
Content-Type: application/json
Accept: application/json

"{{roleId}}"

###
GET {{host}}/user/{{userId}}/role
Authorization: Bearer {{accessToken}}
Accept: application/json

###
